spring.application.name: springboot

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql-database.cpqygy6u09kv.ap-northeast-2.rds.amazonaws.com:3306/FIN_MENTOR
    username: root
    password: gql09so0WOXyqMFj9EJa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      format_sql: true

logging:
  level:
    root: info

coolsms:
  api-key: NCSZGBYEUUF0QADU
  api-secret: PDYDAPMULLX63CPDEVQWTUGITRV4NQAN

jasypt:
  encryptor:
    password: yUZp9wkybdGwzOlUW8Dh8a8g9G2eka0z6vXVCMhCCc2aw1qV8s

custom:
  jwt:
    secretKey: umXvaYXe2LfjbmOsZMzXdmJnM9c4kRcHbSuqZlUyezbIGA1w7Yu7vZ8Oqpk33OrfX8O6XS8qwyEfIxB1g7HzJL
