spring.application.name: springboot

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://bbaek2.synology.me:3306/example
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate.ddl-auto: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    root: info

kakao:
  rest-api-key: 314541b0e482a6d2f2ff97d5c582ed3b
  redirect-uri: http://localhost:5173/auth/login/kakao
  logout-redirect-uri: http://localhost:5173/auth/logout/kakao

naver:
  client-id: IYVENBOBxesP1YgAYgbo
  clinet-secret: DsxNO2Pnnn
  redirect-uri: http://localhost:5173/auth/login/naver

coolsms:
  api-key: NCSZGBYEUUF0QADU
  api-secret: PDYDAPMULLX63CPDEVQWTUGITRV4NQAN