name: Spring Boot Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Docker 버전 확인 (디버깅용)
      - name: Check Docker version
        run: docker --version

      # 4. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Gradle 캐시 설정
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 6. Gradle Wrapper 형식 변경 및 실행 권한 추가
      - name: Convert Gradle wrapper to Unix format
        run: dos2unix ./gradlew

      - name: Add execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      # 7. 애플리케이션 빌드 (Gradle)
      - name: Build application with Gradle
        run: ./gradlew build -x test

      # 8. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # 9. Docker 이미지 푸시
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 1. EC2 서버에 SSH로 접근하여 Docker 컨테이너 업데이트
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest

            docker stop backend || true
            docker rm backend || true

            docker run -d -p 8080:8080 --name backend ${{ secrets.DOCKER_USERNAME }}/backend:latest
